In [2]:
import tensorflow as tf

In [6]:
random_tensor = tf.random.uniform(
    [5,],
    minval = 0,
    maxval = 8,
    dtype = tf.dtypes.float32,
    seed = None,
    name = None,
)
print (random_tensor)

tf.Tensor([5.291007   4.0108805  0.62597656 3.2059984  3.7581415 ], shape=(5,), dtype=float32)


In [10]:
tf.random.set_seed(5)
print (tf.random.uniform(shape=[3,],maxval=3,dtype=tf.int32,seed=10))
print (tf.random.uniform(shape=[3,],maxval=3,dtype=tf.int32,seed=10))
print (tf.random.uniform(shape=[3,],maxval=3,dtype=tf.int32,seed=10))
print (tf.random.uniform(shape=[3,],maxval=3,dtype=tf.int32,seed=10))

tf.Tensor([2 0 1], shape=(3,), dtype=int32)
tf.Tensor([1 0 0], shape=(3,), dtype=int32)
tf.Tensor([0 1 1], shape=(3,), dtype=int32)
tf.Tensor([2 1 2], shape=(3,), dtype=int32)


In [12]:
tf.random.set_seed(5)
print (tf.random.uniform(shape=[3,],maxval=3,dtype=tf.int32,seed=10))
print (tf.random.uniform(shape=[3,],maxval=3,dtype=tf.int32,seed=10))
print (tf.random.uniform(shape=[3,],maxval=3,dtype=tf.int32,seed=10))
print (tf.random.uniform(shape=[3,],maxval=3,dtype=tf.int32,seed=5))

tf.Tensor([2 0 1], shape=(3,), dtype=int32)
tf.Tensor([1 0 0], shape=(3,), dtype=int32)
tf.Tensor([0 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 2 1], shape=(3,), dtype=int32)


In [13]:
tensor_indexed=tf.constant([3,5,7,9,1,2,9,5,6])
print(tensor_indexed)

tf.Tensor([3 5 7 9 1 2 9 5 6], shape=(9,), dtype=int32)


In [14]:
print(tensor_indexed[0:4])

tf.Tensor([3 5 7 9], shape=(4,), dtype=int32)


In [16]:
print(tensor_indexed[1:5+1])

tf.Tensor([5 7 9 1 2], shape=(5,), dtype=int32)


In [17]:
tf.range(2,6)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 4, 5])>

In [18]:
tensor_two_d=tf.constant([[1,2,3],
                          [3,4,5],
                          [4,5,6],
                          [5,6,7],])

In [21]:
print(tensor_two_d[:3,:])

tf.Tensor(
[[1 2 3]
 [3 4 5]
 [4 5 6]], shape=(3, 3), dtype=int32)


In [22]:
print(tensor_two_d[:,0])

tf.Tensor([1 3 4 5], shape=(4,), dtype=int32)


In [23]:
print(tensor_two_d[...,1])

tf.Tensor([2 4 5 6], shape=(4,), dtype=int32)
