In [1]:
import tensorflow as tf
import numpy as np

In [42]:
tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6]], dtype = tf.float32)

In [43]:
s,u,v=tf.linalg.svd(tensor_two_d)
print(s)
print(u)
print(v)


tf.Tensor([100.3663      5.1059036   1.2371687], shape=(3,), dtype=float32)
tf.Tensor(
[[-7.4980810e-04 -3.7569830e-01  9.2674178e-01]
 [ 9.9803799e-01 -5.8300879e-02 -2.2827482e-02]
 [ 6.2606096e-02  9.2490643e-01  3.7500489e-01]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.03044816  0.07330841  0.99684453]
 [ 0.0528536   0.9957936  -0.07484547]
 [ 0.998138   -0.05496572 -0.02644547]], shape=(3, 3), dtype=float32)


In [44]:
A=np.array([[2,6,5,2],
            [2,-2,2,3],
            [1,5,4,0]])
B=np.array([[2,9,0,3,0],
            [3,6,8,-2,2],
            [1,3,5,0,1],
            [3,0,2,0,5]])
print(A.shape)
print(B.shape)

(3, 4)
(4, 5)


In [45]:
print("matmul c:\n")
print(np.matmul(A,B),"\n")

matmul c:

[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]] 



In [46]:
print ("Einsum c=:\n")
print(np.einsum('ij,jk ->ik',A,B))

Einsum c=:

[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]]


In [47]:
A=np.array([[2,6,5,2],
            [2,-2,2,3],
            [1,5,4,0]])
B=np.array([[2,9,0,3],
            [3,6,8,-2],
            [1,3,5,1]])

print(A.shape,B.shape)

print("Hadamond C=: \n")
print(A*B,"\n")

print ("einsum c:= \n")
print(np.einsum('ij,ij ->ij',A,B))

(3, 4) (3, 4)
Hadamond C=: 

[[  4  54   0   6]
 [  6 -12  16  -6]
 [  1  15  20   0]] 

einsum c:= 

[[  4  54   0   6]
 [  6 -12  16  -6]
 [  1  15  20   0]]


In [48]:
A=np.array([[2,6,5,2],
            [2,-2,2,3],
            [1,5,4,0]])
print("Transposed A=: \n")
print(A.T,"\n")
print("Einsum Transpoes A:= \n")
print (np.einsum("ij -> ji ",A))

Transposed A=: 

[[ 2  2  1]
 [ 6 -2  5]
 [ 5  2  4]
 [ 2  3  0]] 

Einsum Transpoes A:= 

[[ 2  2  1]
 [ 6 -2  5]
 [ 5  2  4]
 [ 2  3  0]]


In [49]:
A=np.array([
    [[2,6,5,2],
     [2,-2,2,3],
     [1,5,4,1]],

     [[1,3,1,22],
      [0,2,2,0],
      [1,5,4,1]]  ])

B=np.array([
          [[2,9,0,3,0],
          [3,6,8,-2,2],
          [1,3,5,0,1],
          [3,0,1,1,0]],
          [[1,0,0,3,0],
           [3,0,1,1,0],
           [1,0,2,0,0],
           [3,0,1,1,0]]
      ])
print("batch multiplication C=: \n")
print(np.matmul(A,B), "\n")

print("einsum c =: \n")
print(np.einsum('bij,bjk ->bik',A,B))

batch multiplication C=: 

[[[33 69 75 -4 17]
  [ 9 12 -3 13 -2]
  [24 51 61 -6 14]]

 [[77  0 27 28  0]
  [ 8  0  6  2  0]
  [23  0 14  9  0]]] 

einsum c =: 

[[[33 69 75 -4 17]
  [ 9 12 -3 13 -2]
  [24 51 61 -6 14]]

 [[77  0 27 28  0]
  [ 8  0  6  2  0]
  [23  0 14  9  0]]]


In [50]:
A=np.array([
    [[2,6,5,2],
     [2,-2,2,3],
     [1,5,4,0]],

     [[1,3,1,22],
      [0,2,2,0],
      [1,5,4,1]]
])
print("Sum A=: \n")
print(np.sum(A), "\n")

print ("Einsum A=: \n")
print(np.einsum('bij ->',A))

Sum A=: 

72 

Einsum A=: 

72


In [51]:
A=np.array(
    [[2,6,5,2],
     [2,-2,2,3],
     [1,5,4,0]])
print("Axis 0 Sum A=: \n")
print(np.sum(A, axis = 0),"\n")

print("Einsum A =: \n")
print(np.einsum('ij -> j',A))
print("---------------------------------")

print("Axis 1 Sum A =: \n")
print(np.sum(A,axis = 1),"\n")

print("Einsum A =: \n")
print(np.einsum('ij -> i',A))

Axis 0 Sum A=: 

[ 5  9 11  5] 

Einsum A =: 

[ 5  9 11  5]
---------------------------------
Axis 1 Sum A =: 

[15  5 10] 

Einsum A =: 

[15  5 10]


In [40]:
#Q=batchsize, s_q, modelsize
#K=batchsize, s_k, modelsize

Q=np.random.randn(32,64,512) #bqm
K=np.random.randn(32,1284,512) #bkm
#np.einsum("bqm,bkm -> ,Q,K").shape


In [64]:
A=np.random.randn(2,4,4,2)#bcji
B=np.random.randn(2,4,4,1)#bcik

In [65]:
np.einsum("bcik,bcij -> bckj",B,A).shape

(2, 4, 1, 2)

In [66]:
np.einsum("bcik,bcij -> bckj",B,A)

array([[[[ 0.79568248,  0.18612783]],

        [[-2.206465  ,  1.40063548]],

        [[-2.70772247, -1.55157856]],

        [[ 0.04117308, -1.37082547]]],


       [[[-6.29491621,  1.12718587]],

        [[ 0.49331577,  0.85768677]],

        [[ 0.42175397, -6.02321605]],

        [[ 0.9521864 ,  0.14506139]]]])

In [67]:
np.matmul(np.transpose(B,(0,1,3,2)),A)

array([[[[ 0.79568248,  0.18612783]],

        [[-2.206465  ,  1.40063548]],

        [[-2.70772247, -1.55157856]],

        [[ 0.04117308, -1.37082547]]],


       [[[-6.29491621,  1.12718587]],

        [[ 0.49331577,  0.85768677]],

        [[ 0.42175397, -6.02321605]],

        [[ 0.9521864 ,  0.14506139]]]])

In [57]:
A=np.random.randn(2,4,6,4,2)#bcij
B=np.random.randn(2,4,6,4,1)#bcik

In [60]:
np.einsum("bcdik,bcdij -> bcdkj",B,A).shape

(2, 4, 6, 1, 2)

In [73]:
tensor_three_d=tf.constant([[[1,2,0],
                             [3,5,-1]],
                             
                             [[10,2,0],
                             [1,0,2]],

                             [[5,8,0],
                             [2,7,0]],
                             
                             [[2,1,9],
                             [4,-3,32]]])
print(tensor_three_d.ndim)
print(tensor_three_d.shape)
print(tf.expand_dims(tensor_three_d, axis = 0).shape)

3
(4, 2, 3)
(1, 4, 2, 3)


In [ ]:
x=tf.constant([2,3,4,5])
print(x.shape)
print(tf.expand_dims(x, axis = 0))

(4,)
tf.Tensor([[2 3 4 5]], shape=(1, 4), dtype=int32)


In [80]:
x=tf.constant([[[2,3,4,5]]])
print(x.shape)
x_expanded=tf.expand_dims(x, axis = 0)
print(x_expanded)

(1, 1, 4)
tf.Tensor([[[[2 3 4 5]]]], shape=(1, 1, 1, 4), dtype=int32)


In [81]:
x_squeezed=tf.squeeze(x_expanded , axis =0 )
for i in range(2):
    x_squeezed = tf.squeeze(x_squeezed, axis = 0)

In [82]:
print(x_squeezed)

tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)


In [91]:
tensor_three_d=tf.constant([[[1,2,0],
                             [3,5,-1]],
                             
                             [[10,2,0],
                             [1,0,2]],

                             [[5,8,0],
                             [2,7,0]],
                             
                             [[2,1,9],
                             [4,-3,32]]])

print(tensor_three_d.shape)
x_exp=tf.expand_dims(tensor_three_d, axis = 3)
print(x_exp.shape)
print(tf.squeeze(x_exp, axis = 3))
print(tf.reshape(x_exp, [4,2,3]).shape)

(4, 2, 3)
(4, 2, 3, 1)
tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)
(4, 2, 3)


In [94]:
print(tf.squeeze(x_exp, axis = 3))
print(tf.reshape(x_exp, [4,2,3]).shape)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)
(4, 2, 3)


In [96]:
x_reshape = tf.constant([[3,5,6,6],
                        [4,6,-1,2]])

tf.reshape(x_reshape,[8])

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([ 3,  5,  6,  6,  4,  6, -1,  2])>

In [98]:
x_reshape = tf.constant([[3,5,6,6],
                        [4,6,-1,2]])

tf.reshape(x_reshape,[4,2,1])

<tf.Tensor: shape=(4, 2, 1), dtype=int32, numpy=
array([[[ 3],
        [ 5]],

       [[ 6],
        [ 6]],

       [[ 4],
        [ 6]],

       [[-1],
        [ 2]]])>

In [102]:
t1 = [[1,2,3],
      [4,5,6]]
t2=[[7,8,9],
    [10,11,12]]
print(tf.constant(t1).shape)
print(tf.constant(t2).shape)

tf.concat([t1 , t2], axis = 0)

(2, 3)
(2, 3)


<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])>

In [103]:
t1 = [[1,2,3],
      [4,5,6]]
t2=[[7,8,9],
    [10,11,12]]
print(tf.constant(t1).shape)
print(tf.constant(t2).shape)

tf.concat([t1 , t2], axis = 1)

(2, 3)
(2, 3)


<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])>

In [104]:
t1 = [[[1,2,3],
      [4,5,6]]]
t2=[[[7,8,9],
    [10,11,12]]]
print(tf.constant(t1).shape)
print(tf.constant(t2).shape)

tf.concat([t1 , t2], axis = 0)

(1, 2, 3)
(1, 2, 3)


<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])>

In [ ]:
t1 = [[[1,2,3],
      [4,5,6]]]
t2=[[[7,8,9],
    [10,11,12]]]

print(tf.constant(t1).shape)
print(tf.constant(t2).shape)

tf.concat([t1 , t2], axis = 1)

(1, 2, 3)
(1, 2, 3)


<tf.Tensor: shape=(1, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])>

In [106]:
t1 = [[[1,2,3],
      [4,5,6]]]
t2=[[[7,8,9],
    [10,11,12]]]
print(tf.constant(t1).shape)
print(tf.constant(t2).shape)

tf.concat([t1 , t2], axis = 2)

(1, 2, 3)
(1, 2, 3)


<tf.Tensor: shape=(1, 2, 6), dtype=int32, numpy=
array([[[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]]])>

In [107]:
tf.stack([t1,t2],axis = 0)

<tf.Tensor: shape=(2, 1, 2, 3), dtype=int32, numpy=
array([[[[ 1,  2,  3],
         [ 4,  5,  6]]],


       [[[ 7,  8,  9],
         [10, 11, 12]]]])>

In [109]:
tf.stack([t1,t2,t1],axis = 0)

<tf.Tensor: shape=(3, 1, 2, 3), dtype=int32, numpy=
array([[[[ 1,  2,  3],
         [ 4,  5,  6]]],


       [[[ 7,  8,  9],
         [10, 11, 12]]],


       [[[ 1,  2,  3],
         [ 4,  5,  6]]]])>

In [110]:
t1 = [[1,2,3],
      [4,5,6],
      [5,6,2],
      [5,2,1]]
t2=[[7,8,9],
    [10,11,12],
    [4,5,6],
    [5,6,2]]

In [111]:
tf.stack([t1,t2],axis = 0)

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 5,  6,  2],
        [ 5,  2,  1]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [ 4,  5,  6],
        [ 5,  6,  2]]])>

In [112]:
tf.stack([t1,t2],axis = 1)

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 7,  8,  9]],

       [[ 4,  5,  6],
        [10, 11, 12]],

       [[ 5,  6,  2],
        [ 4,  5,  6]],

       [[ 5,  2,  1],
        [ 5,  6,  2]]])>

In [113]:
tf.stack([t1,t2,t1],axis = 0) 

<tf.Tensor: shape=(3, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 5,  6,  2],
        [ 5,  2,  1]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [ 4,  5,  6],
        [ 5,  6,  2]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 5,  6,  2],
        [ 5,  2,  1]]])>

In [114]:
tf.stack([t1,t2,t1],axis = 1)

<tf.Tensor: shape=(4, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 7,  8,  9],
        [ 1,  2,  3]],

       [[ 4,  5,  6],
        [10, 11, 12],
        [ 4,  5,  6]],

       [[ 5,  6,  2],
        [ 4,  5,  6],
        [ 5,  6,  2]],

       [[ 5,  2,  1],
        [ 5,  6,  2],
        [ 5,  2,  1]]])>

In [116]:
tf.stack([t1,t2,t1],axis = 2)

<tf.Tensor: shape=(4, 3, 3), dtype=int32, numpy=
array([[[ 1,  7,  1],
        [ 2,  8,  2],
        [ 3,  9,  3]],

       [[ 4, 10,  4],
        [ 5, 11,  5],
        [ 6, 12,  6]],

       [[ 5,  4,  5],
        [ 6,  5,  6],
        [ 2,  6,  2]],

       [[ 5,  5,  5],
        [ 2,  6,  2],
        [ 1,  2,  1]]])>

In [118]:
tf.stack([t1,t2],axis = 2)

<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]],

       [[ 5,  4],
        [ 6,  5],
        [ 2,  6]],

       [[ 5,  5],
        [ 2,  6],
        [ 1,  2]]])>

In [120]:
tf.concat([tf.expand_dims(t, axis = 0) for t in[t1,t2]], axis = 0)

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 5,  6,  2],
        [ 5,  2,  1]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [ 4,  5,  6],
        [ 5,  6,  2]]])>

In [2]:
params = tf.constant(['p0', 'p1', 'p2', 'p3', 'p4', 'p5'])
print(params.shape)
params[1:3+1]

(6,)


<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>

In [3]:
tf.gather(params, [0,5,3], axis = 0)
     

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p0', b'p5', b'p3'], dtype=object)>

In [5]:
params = tf.constant([

                      [[0, 1.0, 2.0],
                      [10.0, 11.0, 12.0],
                      [20.0, 21.0, 22.0],
                      [30.0, 31.0, 32.0]]

                       ])
print(params.shape)
tf.gather(params, [2,0], axis = 1)

(1, 4, 3)


<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[20., 21., 22.],
        [ 0.,  1.,  2.]]], dtype=float32)>

In [6]:
indices = [[2]]

params = [['a', 'b'],
          ['c', 'd'],
          ['e', 'f']]

tf.gather_nd(params, indices)

<tf.Tensor: shape=(1, 2), dtype=string, numpy=array([[b'e', b'f']], dtype=object)>

In [7]:
indices = [[0,1],
           [1,0]],


params = [[['a0', 'b0'],
           ['c0', 'd0']],

           [['a1', 'b1'],
            ['c1', 'd1']]]

In [8]:
tensor_two_d=tf.constant([[1,2,0],
                          [3,5,-1],
                          [1,5,6],
                          [2,3,8]])

print(tensor_two_d.shape)
     

(4, 3)


In [9]:
tensor_two_d = [[1,2,0],
                [3,],
                [1,5,6,5,6],
                [2,3]]

tensor_ragged = tf.ragged.constant(tensor_two_d)
print(tensor_ragged)
     

<tf.RaggedTensor [[1, 2, 0], [3], [1, 5, 6, 5, 6], [2, 3]]>


In [10]:
print(tf.RaggedTensor.from_row_lengths(
      values=[3,1,4,1,5,9,2,6],
      row_lengths=[4,0,3,1,0]))
     

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


In [11]:
tf.gather_nd(params, indices, batch_dims = 0)

<tf.Tensor: shape=(1, 2, 2), dtype=string, numpy=
array([[[b'c0', b'd0'],
        [b'a1', b'b1']]], dtype=object)>

In [12]:
tensor_sparse = tf.SparseTensor(
    indices=[[1,1],[3,4]], values = [11,56], dense_shape = [5,6]
)

In [13]:
print(tensor_sparse)

SparseTensor(indices=tf.Tensor(
[[1 1]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([11 56], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))


In [14]:
tf.sparse.to_dense(tensor_sparse)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 56,  0],
       [ 0,  0,  0,  0,  0,  0]])>

In [15]:
tensor_string = tf.constant(['hello', 'i am', 'a string'])
print(tensor_string)

tf.Tensor([b'hello' b'i am' b'a string'], shape=(3,), dtype=string)


In [16]:
tf.strings.join(tensor_string, separator ="")
     

<tf.Tensor: shape=(), dtype=string, numpy=b'helloi ama string'>

In [17]:
tf.strings.join(tensor_string, separator =' ')
     

<tf.Tensor: shape=(), dtype=string, numpy=b'hello i am a string'>

In [18]:
tf.strings.join(tensor_string, separator ="**")
     

<tf.Tensor: shape=(), dtype=string, numpy=b'hello**i am**a string'>

In [19]:
x = tf.constant([1,2])
     

In [20]:
x_var = tf.Variable(x)
print(x_var)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2])>


In [21]:
x_var = tf.Variable(x, name = 'var1')
print(x_var)

<tf.Variable 'var1:0' shape=(2,) dtype=int32, numpy=array([1, 2])>


In [22]:
x_var.assign_sub([3,4])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([-2, -2])>

In [23]:
x_var.assign_add([5,8])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([3, 6])>

In [24]:
with tf.device('GPU:0'):
  x_var = tf.Variable(0.2)

print(x_var)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.20000000298023224>


In [25]:
print(x_var.device)
     

/job:localhost/replica:0/task:0/device:CPU:0


In [26]:
with tf.device('GPU:0'):
  x_var = tf.Variable(0.2)

with tf.device('CPU:0'):
  x_tensor = tf.constant(0.2)

print(x_var.device)

print(x_tensor.device)


/job:localhost/replica:0/task:0/device:CPU:0
/job:localhost/replica:0/task:0/device:CPU:0


In [27]:
with tf.device('CPU:0'):
  x_1 = tf.constant([1,3,4])
  x_2 = tf.constant([1])

with tf.device('GPU:0'):
  x_3 = x_1 + x_2

print(x_1, x_1.device)
print(x_2, x_2.device)
print(x_3, x_3.device)

tf.Tensor([1 3 4], shape=(3,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([1], shape=(1,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([2 4 5], shape=(3,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
