In [2]:
! pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/390.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/390.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/390.3 MB ? eta -:--:--
   ---------------------------------------- 0.8/390.3 MB 2.0 MB/s eta 0:03:18
   ---------------------------------------- 1.6/390.3 MB 2.9 MB/s eta 0:02:15
   ---------------------------------------- 1.6/390.3 MB 2.9 MB/s eta 0:02:15
   ---------------------------------------- 2.4/390.3 MB 2.9 MB/s eta 0:02:16
   ---------------------------------------- 3.7/390.3 MB 3.5 MB/s eta 0:01:50
   ---------------------------------------- 4.5/390.3 MB 3.2 MB/s eta 0:02:01
    --------------------------------------- 5.2/390.3 MB 3.3 MB/s eta 0:01:56
    --------------------------------------- 6.3/390.3 MB 3.5 MB/s eta 0:01:50
    --------------------------------------- 6.8/390.3 MB 3.6 MB/s eta 0:01:47
    ---


[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: C:\Users\Razieh\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [1]:
import tensorflow as tf 

In [2]:
tensor_zero_d=tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
tensor_one_d=tf.constant([2,-1,5,8,9],dtype=tf.float32)
print(tensor_one_d )

tf.Tensor([ 2. -1.  5.  8.  9.], shape=(5,), dtype=float32)


In [4]:
tensor_two_d=tf.constant([
    [2,4,-1],
    [3,10,-9],
    [3,10,-5],
    [1,2,-4]
    ])
print(tensor_two_d)

tf.Tensor(
[[ 2  4 -1]
 [ 3 10 -9]
 [ 3 10 -5]
 [ 1  2 -4]], shape=(4, 3), dtype=int32)


In [5]:
tensor_three_d=tf.constant([
    [[1,2,3],
     [3,4,5]],
    [[4,5,6],
     [5,6,7]],
    [[6,7,8],
    [7,8,9]],
])
print(tensor_three_d)

tf.Tensor(
[[[1 2 3]
  [3 4 5]]

 [[4 5 6]
  [5 6 7]]

 [[6 7 8]
  [7 8 9]]], shape=(3, 2, 3), dtype=int32)


In [6]:
print(tensor_three_d.shape)

(3, 2, 3)


In [7]:
print(tensor_three_d.ndim)

3


In [8]:
tensor_four_d = tf.constant([
[
    [[1,2,3],
     [3,4,5]],
    [[4,5,6],
     [5,6,7]],
    [[6,7,8],
    [7,8,9]],],

  [
    [[1,2,3],
     [3,42,5]],
    [[4,5,6],
     [5,16,7]],
    [[96,7,8],
    [7,48,9]],],

 [
    [[1,2,3],
     [3,42,5]],
    [[4,5,6],
     [5,16,7]],
    [[96,7,8],
    [7,48,9]],],
])
print(tensor_four_d)

tf.Tensor(
[[[[ 1  2  3]
   [ 3  4  5]]

  [[ 4  5  6]
   [ 5  6  7]]

  [[ 6  7  8]
   [ 7  8  9]]]


 [[[ 1  2  3]
   [ 3 42  5]]

  [[ 4  5  6]
   [ 5 16  7]]

  [[96  7  8]
   [ 7 48  9]]]


 [[[ 1  2  3]
   [ 3 42  5]]

  [[ 4  5  6]
   [ 5 16  7]]

  [[96  7  8]
   [ 7 48  9]]]], shape=(3, 3, 2, 3), dtype=int32)


In [9]:
import numpy as np

In [10]:
np_array=np.array([1,2,3])
print (np_array)

[1 2 3]


In [11]:
eye_tensor=tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [12]:
print(eye_tensor*3)

tf.Tensor(
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]], shape=(3, 3), dtype=float32)


In [13]:
eye_tensor=tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.bool,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[ True False False]
 [False  True False]
 [False False  True]], shape=(3, 3), dtype=bool)


In [14]:
eye_tensor=tf.eye(
    num_rows=5,
    num_columns=3,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(5, 3), dtype=float32)


In [15]:
eye_tensor=tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[3,],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]], shape=(3, 5, 5), dtype=float32)
