In [4]:
import tensorflow as tf

In [5]:
random_tensor = tf.random.uniform(
    [5,],
    minval = 0,
    maxval = 8,
    dtype = tf.dtypes.float32,
    seed = None,
    name = None,
)
print (random_tensor)

tf.Tensor([4.512287  5.671748  6.285118  7.0455027 2.5170994], shape=(5,), dtype=float32)


In [6]:
tf.random.set_seed(5)
print (tf.random.uniform(shape=[3,],maxval=3,dtype=tf.int32,seed=10))
print (tf.random.uniform(shape=[3,],maxval=3,dtype=tf.int32,seed=10))
print (tf.random.uniform(shape=[3,],maxval=3,dtype=tf.int32,seed=10))
print (tf.random.uniform(shape=[3,],maxval=3,dtype=tf.int32,seed=10))

tf.Tensor([2 0 1], shape=(3,), dtype=int32)
tf.Tensor([1 0 0], shape=(3,), dtype=int32)
tf.Tensor([0 1 1], shape=(3,), dtype=int32)
tf.Tensor([2 1 2], shape=(3,), dtype=int32)


In [7]:
tf.random.set_seed(5)
print (tf.random.uniform(shape=[3,],maxval=3,dtype=tf.int32,seed=10))
print (tf.random.uniform(shape=[3,],maxval=3,dtype=tf.int32,seed=10))
print (tf.random.uniform(shape=[3,],maxval=3,dtype=tf.int32,seed=10))
print (tf.random.uniform(shape=[3,],maxval=3,dtype=tf.int32,seed=5))

tf.Tensor([2 0 1], shape=(3,), dtype=int32)
tf.Tensor([1 0 0], shape=(3,), dtype=int32)
tf.Tensor([0 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 2 1], shape=(3,), dtype=int32)


In [8]:
tensor_indexed=tf.constant([3,5,7,9,1,2,9,5,6])
print(tensor_indexed)

tf.Tensor([3 5 7 9 1 2 9 5 6], shape=(9,), dtype=int32)


In [9]:
print(tensor_indexed[0:4])

tf.Tensor([3 5 7 9], shape=(4,), dtype=int32)


In [10]:
print(tensor_indexed[1:5+1])

tf.Tensor([5 7 9 1 2], shape=(5,), dtype=int32)


In [11]:
tf.range(2,6)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 4, 5])>

In [12]:
tensor_two_d=tf.constant([[1,2,3],
                          [3,4,5],
                          [4,5,6],
                          [5,6,7],])

In [13]:
print(tensor_two_d[:3,:])

tf.Tensor(
[[1 2 3]
 [3 4 5]
 [4 5 6]], shape=(3, 3), dtype=int32)


In [14]:
print(tensor_two_d[:,0])

tf.Tensor([1 3 4 5], shape=(4,), dtype=int32)


In [15]:
print(tensor_two_d[...,1])

tf.Tensor([2 4 5 6], shape=(4,), dtype=int32)


In [16]:
tensor_three_d=tf.constant([
    [[2,20,3],
     [3,4,5]],
    [[4,78,6],
     [5,46,7]],
    [[6,103,8],
    [7,8,999]],
])


In [17]:
print(tensor_three_d[0,0,:])

tf.Tensor([ 2 20  3], shape=(3,), dtype=int32)


In [18]:
x_abs=tf.constant ([-2.25,3.25])
tf.abs(x_abs)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [19]:
tf.abs(tf.constant(-0.2))

<tf.Tensor: shape=(), dtype=float32, numpy=0.20000000298023224>

In [20]:
x_abs_complex=tf.constant([-2.25+4.75j])
tf.abs(x_abs_complex)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([5.25594901])>

In [21]:
tf.sqrt ((-2.25)**2+4.75**2)

<tf.Tensor: shape=(), dtype=float32, numpy=5.255949020385742>

In [22]:
x_1 = tf.constant ([5,3,6,6,4,6],dtype=tf.int32)
x_2 = tf.constant ([7,6,2,6,7,11],dtype=tf.int32)
print (tf.divide (x_1 , x_2))

tf.Tensor([0.71428571 0.5        3.         1.         0.57142857 0.54545455], shape=(6,), dtype=float64)


In [23]:
x_1 = tf.constant ([[5,3,6,6,4,6],], dtype=tf.float32)
x_2 = tf.constant ([[7],[5],[3]], dtype = tf.float32)

print(x_1.shape)
print(x_2.shape)
print(tf.math.multiply(x_1,x_2))

(1, 6)
(3, 1)
tf.Tensor(
[[35. 21. 42. 42. 28. 42.]
 [25. 15. 30. 30. 20. 30.]
 [15.  9. 18. 18. 12. 18.]], shape=(3, 6), dtype=float32)


In [24]:
x_argmax=tf.constant([[2,20,30,3,6],
                      [3,11,16,1,8],
                      [14,45,23,5,27]])

print (x_argmax.shape)
print (tf.math.argmax(x_argmax,0))

(3, 5)
tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)


In [25]:
x_argmax=tf.constant ([200,120,130,3,6])
print (tf.math.argmax(x_argmax))
     


tf.Tensor(0, shape=(), dtype=int64)


In [26]:
x_argmax=tf.constant([200,120,130,300,6])
print(tf.math.argmax(x_argmax))

tf.Tensor(3, shape=(), dtype=int64)


In [27]:
x=tf.constant([[2,2],[3,3]])
y=tf.constant([[3,0],[1,4]])
tf.pow(x,y)
     


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 8,  1],
       [ 3, 81]])>

In [28]:
tf.pow(tf.constant(2),tf.constant(3))

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [29]:
tensor_two_d=tf.constant([
    [1,-2,0],
    [3,5,100],
    [1,5,6],
    [2,3,8]
    ])
print(tensor_two_d.shape)
print(tf.math.reduce_sum(tensor_two_d,axis=0,keepdims=False,name=None))

(4, 3)
tf.Tensor([  7  11 114], shape=(3,), dtype=int32)


In [30]:
tf.math.top_k(tensor_two_d,k=1)
     

TopKV2(values=<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[  1],
       [100],
       [  6],
       [  8]])>, indices=<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[0],
       [2],
       [2],
       [2]])>)

In [31]:
x_1 = tf.constant ([[1,2,0],
                    [3,5,-1]])
x_2 = tf.constant ([[1,2,0,2],
                    [3,5,-1,2],
                    [4,5,6,0]])
print(x_1.shape,x_2.shape)
tf.linalg.matmul(
x_1,x_2,transpose_a=False,transpose_b=False, adjoint_a=False, adjoint_b=False,
a_is_sparse=False, b_is_sparse=False, output_type=None
)

(2, 3) (3, 4)


<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[  7,  12,  -2,   6],
       [ 14,  26, -11,  16]])>

In [32]:
print(x_1@x_2)

tf.Tensor(
[[  7  12  -2   6]
 [ 14  26 -11  16]], shape=(2, 4), dtype=int32)


In [33]:
x_1 = tf.constant([[1,2,0]])

x_2 = tf.constant([[1,2],
                   [3,5],
                   [4,5]])

x_3 = tf.constant([[1,2,0,2],
                   [3,5,-1,2]])

print(x_1.shape, x_2.shape, x_3.shape, tf.transpose(x_2).shape)

print(tf.transpose(x_3)@tf.transpose(x_2))

tf.linalg.matmul(
    x_3, x_2, transpose_a = True,transpose_b = True, adjoint_a = False, adjoint_b = False,
    a_is_sparse = False, b_is_sparse = False, output_type=None, name=None
)

(1, 3) (3, 2) (2, 4) (2, 3)
tf.Tensor(
[[ 7 18 19]
 [12 31 33]
 [-2 -5 -5]
 [ 6 16 18]], shape=(4, 3), dtype=int32)


<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 7, 18, 19],
       [12, 31, 33],
       [-2, -5, -5],
       [ 6, 16, 18]])>

In [35]:
x_1 = tf.constant([[[1,2],
                    [3,5]],

                   [[10,2],
                    [1,0]],

                   [[5,8],
                    [2,7]]])

x_2 = tf.constant([[[5,1,4],
                    [34,15,1]],

                   [[1,2,2],
                    [5,3,2]],

                   [[2,2,3],
                    [1,1,1]]])
print(x_1)
print(x_2)

print(tf.linalg.matmul(x_1,x_2))

tf.Tensor(
[[[ 1  2]
  [ 3  5]]

 [[10  2]
  [ 1  0]]

 [[ 5  8]
  [ 2  7]]], shape=(3, 2, 2), dtype=int32)
tf.Tensor(
[[[ 5  1  4]
  [34 15  1]]

 [[ 1  2  2]
  [ 5  3  2]]

 [[ 2  2  3]
  [ 1  1  1]]], shape=(3, 2, 3), dtype=int32)
tf.Tensor(
[[[ 73  31   6]
  [185  78  17]]

 [[ 20  26  24]
  [  1   2   2]]

 [[ 18  18  23]
  [ 11  11  13]]], shape=(3, 2, 3), dtype=int32)


In [36]:
tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6],
                            [2,3,8]], dtype = tf.float16)
tensor_out_d = tf.constant([[1,0,0],
                            [0,5,0],
                            [0,0,6],
                            [0,0,0]], dtype = tf.float16)
tf.linalg.band_part(tensor_two_d, 0,0)

<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 6.],
       [0., 0., 0.]], dtype=float16)>

In [37]:
tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6],
                            [2,3,8]], dtype = tf.float16)
tensor_out_d = tf.constant([[1,0,0],
                            [0,5,0],
                            [0,0,6],
                            [0,0,0]], dtype = tf.float16)
tf.linalg.band_part(tensor_two_d, -1,0)


<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[1., 0., 0.],
       [3., 5., 0.],
       [1., 5., 6.],
       [2., 3., 8.]], dtype=float16)>

In [38]:
tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6],
                            [2,3,8]], dtype = tf.float16)
tensor_out_d = tf.constant([[1,0,0],
                            [0,5,0],
                            [0,0,6],
                            [0,0,0]], dtype = tf.float16)
tf.linalg.band_part(tensor_two_d, 0,-1)


<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[  1.,  -2.,   0.],
       [  0.,   5., 100.],
       [  0.,   0.,   6.],
       [  0.,   0.,   0.]], dtype=float16)>

In [39]:
tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6]], dtype = tf.float32)
tensor_two_d_inv = tf.linalg.inv(tensor_two_d)

In [42]:
tensor_two_d @ tensor_two_d_inv

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.0000000e+00,  7.4505806e-09,  0.0000000e+00],
       [ 1.6391277e-07,  1.0000000e+00,  1.6391277e-07],
       [-5.2154064e-08,  7.4505806e-08,  1.0000000e+00]], dtype=float32)>